### ISSUE TITLE
jobs list takes forever

### ISSUE THREAD

**Issue by paultag** [paultag/moxie#69]
something is going nuts in the template, I can feel it

**Comment by paultag** [comment]
This is actually perhaps the get jobs overview - rather then doing a JOIN like it should, it's doing N queries.

https://github.com/paultag/moxie/blob/master/moxie/app.py#L50-L55

This is silly stuff

**Comment by mileswwatkins** [comment]
Solved by https://github.com/paultag/moxie/pull/72?

**Comment by mileswwatkins** [comment]
Totally solved, @paultag close this cat down.
