### ISSUE TITLE
Create option for Jobs to not run at certain times

### ISSUE THREAD

**Issue by mileswwatkins** [paultag/moxie#78]
Either do this through a "default time" (or date) for `Job`s to run, or "blackout hours" during which a `Job` won't automatically be run. Both of these could be temporarily overridden by an SSH/Slack `run [Job name]`.

@rshorey, @paultag, preference on which I implement?

**Comment by rshorey** [comment]
I would probably do a default time, probably because what happens if it tries to go during blackout hours seems like a confusing question to me.

**Comment by paultag** [comment]
Hurm, interesting idea. What's the motivation? I'd love to understand the problem :)

**Comment by mileswwatkins** [comment]
This is more or less addressed by my PR that switched Moxie to Cron scheduling (instead of just using an `interval`). Basically, for Open States and municipal OCD scrapers we don't want jobs to run automatically during local business hours.

But you could also apply this to other situations. Say you know your company's server will be down for an hour each night and want to avoid runs during that time. Or you have a stock market analysis tool that needs to run hourly _only_ during the market's active hours.

**Comment by mileswwatkins** [comment]
But I think Cron fixes this issue!
