### ISSUE TITLE
alerts

### ISSUE THREAD

**Issue by paultag** [paultag/moxie#8]
add alerts 

 - [x] email (critical)
 - [ ] webhooks
 - [x] slack
 - [ ] kgb
 - [ ] github

**Comment by tianon** [comment]
(IRC with fancy colors, of course)

**Comment by tianon** [comment]
https://github.com/devunt/aioirc might be more useful / easier to plug in than kgb (worth a look)

**Comment by paultag** [comment]
deps on #43

**Comment by paultag** [comment]
Groundwork for email in https://github.com/paultag/moxie/commit/28dac32a936b1707a963470000161a7211eb006c

**Comment by paultag** [comment]
Email has been test deployed to the sunlight moxie instance; seems to work

**Comment by paultag** [comment]
![](http://i.imgur.com/s0xlU0d.png)

**Comment by paultag** [comment]
Updated to add GitHub alert, so that we can file a bug for each new failure :)

**Comment by paultag** [comment]
slack is happy and configurable via the tag interface

**Comment by paultag** [comment]
good enough for now; closing this
